const STOP_LOADING = 'STOP_LOADING';
const SET_IS_LAST = 'SET_IS_LAST';
const SET_ALL_USERS = 'SET_ALL_USERS';
const SET_ALL_MESSAGES = 'SET_ALL_MESSAGES';
const CONNECTED = 'CONNECTED';
const DISCONNECTED = 'DISCONNECTED';
const SET_LOGIN_STATUS = 'SET_LOGIN_STATUS';
const DIALOG_MESSAGE = {
  JUST_LEFT: 'just left',
  JUST_COME: 'just entered',
};

export {
  STOP_LOADING,
  SET_IS_LAST,
  SET_ALL_USERS,
  SET_ALL_MESSAGES,
  CONNECTED,
  DISCONNECTED,
  SET_LOGIN_STATUS,
  DIALOG_MESSAGE,
};